name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Copy files to server
      uses: nvlab-pro/cloudmenu@master
      with:
        rm: true
        source: "./*"
        target: "domains/cloudmenu.online/public_html"
      secrets:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
