name: Deploy to Server NWMS.Cloud

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy via SFTP
      uses: appleboy/scp-action@master
      with:
        host: nwms.cloud
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        source: "./*"
        target: "/var/www/nwms.cloud"
